### ISSUE TITLE
Unable to use in Electron build with asar

### ISSUE THREAD

**Issue by has-n** [karaggeorge/macos-audio-devices#18]
The package works fine in development builds but not production builds unless asar is turned off. 

I'm using electron-builder, if it matters. Pretty standard configuration.

**Comment by chinarui-na** [comment]
Is it resolved?

**Comment by has-n** [comment]
The issue is upstream: https://github.com/sindresorhus/electron-util/issues/53#issue-981786403

**Comment by chinarui-na** [comment]
How to fix it ？

**Comment by chinarui-na** [comment]
> The issue is upstream: https://github.com/sindresorhus/electron-util/issues/53#issue-981786403 

How to fix it ?

**Comment by has-n** [comment]
You can set asarUnpack to point to this module in your electron builder configuration.

**Comment by chinarui-na** [comment]
> You can set asarUnpack to point to this module in your electron builder configuration.

i use electron-builder and i set it in my configuration
```
"asarUnpack": [
          "**/node_modules/macos-audio-devices/**/*"
],
```
i can see app.asar.unpacked who include `/node_modules/macos-audio-devices/`
but also got error
```
Command failed with ENOTDIR
/Contents/Resources/app.asar/audio-devices list --output --json
```
i know the path is error,but dont know how to fix it. can you help me ? thanks.

**Comment by has-n** [comment]
Use the latest build of `electron-util` : https://github.com/sindresorhus/electron-util/releases/tag/v0.17.2
